### ISSUE TITLE
Named deployment to support multiple deployments per module

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/ignition#109]
Currently a module can be deployed to completion once. It can be rerun if only partially executed or errored; but while display the results of the previous run if rerun on a successful deploy.

To support using a module multiple time we could introduce the concept of a deployment id. So a module could have multiple deployments, each with a unique module id.

This raises design questions about composing sections of the module that refer to singleton instances of contracts on a deploy relative to contracts which are redeployed as new instances each run.

**Comment by alcuadrado** [comment]
I think we can have a "global" deployment id, so that we scope everything by it. That is, the journal files, deployment artifacts, or whatever we want to store.

We should default de deployment id to something like `"network-${chainId}"`.

**Comment by kanej** [comment]
This is something we want to support. Right now there is one journal file per module. We want to switch it to a folder structure that supports different deployment ids and chains and whatever other feature the journal needs scoped by.

The next step is to confirm the list of features to scope by (currently chainId and deploymentId) and design a folder layout that will support them.
