### ISSUE TITLE
Command to list previous deployments against a module

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/ignition#111]
We do currently do show the deployed contracts if a successful module deploy is rerun. However, a user may be understandably reluctant to run the `deploy` command when only information is being sought. We should add an `ignition-info` command that displays the success/unsuccessful deployed contracts, their status and address.

We would look to leverage hh scopes to get subtasks when they become available and improve the command to `npx hardhat ignition info`.

The display should be scoped if a network is provided, but show each network one after another and the contracts deployed to each.

Maybe something like `npx hardhat ignition-info --network polygon`:

```shell

polygon
-------

Contract A   deployed   0x0000123
Contract B   errored
Contract C   pending

```

and `npx hardhat ignition-info`:

```shell
mainnet
-------
Contract A   deployed   0x0000123
Contract B   deployed   0x0000124
Contract C   deployed   0x0000125


polygon
-------

Contract A   deployed   0x0000123
Contract B   errored
Contract C   pending
```

We should investigate table layouts in ink.

**Comment by zoeyTM** [comment]
Editing the format to better suit ignition's needs:

```
MyModule.js
____________

mainnet
-------
Foo   deployed   0x123
Bar   pending

polygon
-------
Foo   deployed   0x456
Bar   errored


OtherModule.js
_______________

hardhat
-------
Bar   errored
```
