### ISSUE TITLE
Feedback/Questions

### ISSUE THREAD

**Issue by 0xdavinchee** [NomicFoundation/ignition#127]
## Context
A bit about myself: I am a developer at Superfluid working mostly on the protocol side.

I remember seeing an announcement regarding Ignition a while back and decided to give it a try today. 

I wanted to see if we could eventually replace it as our de-facto deployment for testing/prod as it seems to improve a lot of the UX pain points surrounding deployment, both internally and externally-we have an ad-hoc way of distributing our contracts which allows external devs to test against our contracts locally.

I also like how it aims to standardize smart contract deployments and distributions. 

Below I've listed some questions/feedback after just playing around with it a bit.

Really cool and bleeding-edge stuff! 🔥 

## Code
I essentially replicated what one of our [contracts](https://github.com/0xdavinchee/protocol-monorepo/blob/ignition/packages/ethereum-contracts/contracts/utils/SuperfluidFrameworkDeployer.sol) is doing but with a module using Ignition: [TestFrameworkModule.js](https://github.com/0xdavinchee/protocol-monorepo/blob/ec62c2e8229338b3d7f66ce09865c4f34d7d93f1/packages/ethereum-contracts/ignition/TestFrameworkModule.js)

## Questions
- Are there plans to make this work in a CI environment (Github Actions)? Including with retries? More specifically: are there any plans on some best practices way of publishing/outputting the relevant deployment information from the run? More specifically referring to this section of [this article](https://forum.openzeppelin.com/t/a-case-for-secure-web3-operations/32141#reproducible-auditable-deployments-2).
  - The `.journal` output seems like it has this information, one can link the pushed code at a commit to the bytecode deployed from a specific CI/CD run.
- Are there plans to incorporate automatic contract verification? 
  - If the contract verification config is included in hardhat config, it should be doable. 
- I noticed in the ENS.js example there is something called `buildSubgraph`, what is this?
  - The naming is a tiny bit confusing as it might be mixed up with The Graph's Subgraph, but it's not a big problem.
- Is there going to be support for proxies/contract upgrading or the hardhat upgrades plugin?
- `npx hardhat plan` is broken when you include a library as part of the deployment:
```
Error: Unknown vertex type: HardhatLibrary
    at parseType (node_modules/@ignored/hardhat-ignition/src/plan/utils.ts:20:13)
    at Object.getSummaryLists (node_modules/@ignored/hardhat-ignition/src/plan/utils.ts:60:18)
    at Renderer.write (node_modules/@ignored/hardhat-ignition/src/plan/index.ts:64:32)
    at SimpleTaskDefinition.action (node_modules/@ignored/hardhat-ignition/src/index.ts:204:16)
    at async Environment._runTaskDefinition (node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at async Environment.run (node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at async main (node_modules/hardhat/src/internal/cli/cli.ts:272:7)
```

**Comment by kanej** [comment]
Firstly, @0xdavinchee, this is great feedback, we deeply appreciate your efforts here.

Taking the questions and issues one by one:

> Are there plans to make this work in a CI environment (Github Actions)? Including with retries? More specifically: are there any plans on some best practices way of publishing/outputting the relevant deployment information from the run? More specifically referring to this section of [this article](https://forum.openzeppelin.com/t/a-case-for-secure-web3-operations/32141#reproducible-auditable-deployments-2).
>
> * The .journal output seems like it has this information, one can link the pushed code at a commit to the bytecode deployed from a specific CI/CD run.

The openzeppelin article you link lists the sort of problems we are wanting to tackle. Our retry mechanism right now works by storing data as the deployment progresses (the journal), to allow retries; we need to consider how that should adapt for the github actions scenario.

We want reproducible build artifacts from CI to feed into reproducible deployments across multiple chains, and to have the providence of bytecode run all the way back to the solidity code.

You can see some initial WIP thinking on this here: https://github.com/NomicFoundation/ignition/blob/a092ea7fa8b8f97a78144aff5af0712c3ce0ac63/docs/distributable-deployments.md

> Are there plans to incorporate automatic contract verification? 

Yes. This requirement impacts the information we distribute with a reusable ignition package (for instance, locally pulling in the uniswap ignition building block should give you enough info to verify the contracts it exposes), so we will need to get to the other side of distributing reusable deployment code before we tackle it.

I have opened an issue for verification here, so anyone can feed in requirements: https://github.com/NomicFoundation/ignition/issues/128

> I noticed in the ENS.js example there is something called buildSubgraph, what is this? 

The subgraph is a representation of a part of the dependency graph of on-chain transactions that ignition executes during a deploy. The module a user builds with the api is a _subgraph_ with some extra constraints. We suspect we should make subgraphs entirely internal, and expose only more constrained versions (like Modules) through the user facing api, but the ENS example hasn't been updated to reflect that. Either way we will rename the concept to avoid confusion with the Graph's subgraphs (https://github.com/NomicFoundation/ignition/issues/129).

> Is there going to be support for proxies/contract upgrading or the hardhat upgrades plugin?

We want to support proxies and contract upgrade-ability. We don't have any examples of integrating upgrade-ability into an ignition module yet, but in the next few weeks we will be digging in on this to see how the api needs to change to support it properly (https://github.com/NomicFoundation/ignition/issues/130).

> npx hardhat plan is broken when you include a library as part of the deployment

That is a bug and we will get it fixed (https://github.com/NomicFoundation/ignition/issues/131)

Thanks again.

**Comment by 0xdavinchee** [comment]
hey @kanej, thanks for answering my questions and creating issues for some of the things I brought up. 

I like the direction Ignition is moving in and really looking forward to following along with progress, please let me know if I can help out in any other way! 🔥 

Also, feel free to close this issue if you want, the other issues opened makes this one redundant.
