### ISSUE TITLE
Support direct imports of contracts in npm packages

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/ignition#136]
To deploy the openzeppelin timelock controller the current steps are:

1. `npm install @openzeppelin/contracts`
2. `echo 'import "@openzeppelin/.../timlock.sol"' > ./contracts/workaround.sol`
3. In ignition module `m.deploy("TimelockController")`

If possible it would be good to be able to skip step 2. This likely means changes in hh, so may not justify the effort.

**Comment by kanej** [comment]
Alternately it may be solved by distributable deployments if openzeppelin used them for the timelock controller.

**Comment by kanej** [comment]
I suspect this is one to wait for later stages.

**Comment by alcuadrado** [comment]
Closing as this is out of scope for Ignition. 

The loading of artifacts depends on the integrator providing an [`ArtifactResolver`](https://github.com/NomicFoundation/ignition/blob/316ec19b1df431a665e523cefd88ef4db7f0bf31/packages/core/src/new-api/types/artifact.ts#L21-L24), and in the case of the plugin that's backed by Hardhat.
