### ISSUE TITLE
Replace artifact api calls with single destructuring `getArtifact`

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/ignition#155]
We currently support `m.getBytesForArtifact("Foo")` within the api but need a similar function for getting an abi.

Instead of adding functions for each property of artifact we should add a `getArtifact` that returns an artifact future that can be destructured into bytes/abi futures or others as we need to add them.

**Comment by zoeyTM** [comment]
Adding onto this, allowing the `getArtifact` future to be used anywhere a "normal" artifact would be passed as a parameter (i.e. `ArtifactContract`, `Event`, etc.)
