### ISSUE TITLE
Add module parameters into the new api

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/ignition#226]
For our initial pass we are going to avoid explicit module -> submodule parameter passing. Instead a module will be able to access the global parameters context. If the parameter context is accessed a default value has to be provided as well (this is a constraint we can loosen later with validation of required parameters).

Only solidity parameter value types can be passed via `getOptionalParameter`

Example: 

```
const supply = m.getOptionalParameter<number>("supply", 1000);
const ticker = m.getOptionalParameter<string>("ticker", "ETH");

const c = m.contract("Token", [ticker, supply]);
```

The return value should be a value, not a future. The parameters provided will be injected into the constructor constructor constructor.

**Comment by alcuadrado** [comment]
Already fixed by @zoeyTM  and me
