### ISSUE TITLE
Send needs to pass undefined for data

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/ignition#314]
Currently:
```
m.send("test send", "0xtest", 0n, "test-data", { id: "send" });
```

Is allowed, but skipping the data (or sending data but not value) creates a type error unless you explicitly pass undefined:
```
m.send("test send", "0xtest", 0n, { id: "send" }); // type error
```

**Comment by alcuadrado** [comment]
This is intentional. You can also use `"0x"` to pass no data.
