### ISSUE TITLE
base result on execution state not messages

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/ignition#320]
Created in response to: https://github.com/NomicFoundation/ignition/pull/306#discussion_r1266538942

The current execution inner loop builds up the final result by capturing success messages from completed futures. This duplicates the information in the execution state.

We should stop passing around these messages and calculate the final result off of the execution state. This will lead to less concepts within the batch inner loop and give us more flexibility in the result object.

**Comment by alcuadrado** [comment]
Already implemented in the development branch
