### ISSUE TITLE
move timeout check to be on tick only

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/ignition#321]
Based on feedback here: https://github.com/NomicFoundation/ignition/pull/306#discussion_r1271466691

We check for timeouts in two places: when seeing if a receipt is available in the per future checks and secondly when waiting for a new block.

The proposal is eliminate the new block check. Relying only on the per future check.

I suspect my original design was skewed by pushing this use case with a test that did not generate a block; therefore if a block is not minted (or massively delayed) we need this further check. This is likely an unrealistic scenario.

It would be better to add a test that creates timeouts via high gas limits, rather than relying on the case above: https://github.com/NomicFoundation/ignition/pull/306#discussion_r1266564134

**Comment by alcuadrado** [comment]
Now that we have gas bumping in place, the timeout logic drastically changed, and this is no longer relevant.
