### ISSUE TITLE
check error display

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/ignition#327]
Ensure we provide a clear display of each error type at the cli.

For each of the error types in todo we should check that causing the error from the command line shows the error message clearly (ideally with the category i.e. validation error: ...).

## TODO

- [ ] validation errors
- [ ] reconciliation errors
  - [ ] Reconciliation future failure
  - [ ] missing futures warnings
- [ ] execution reverts
- [ ] other errors?

**Comment by zoeyTM** [comment]
Validation error:

![Image](https://github.com/NomicFoundation/ignition/assets/14796043/810b8546-170c-448c-82df-deb9c31e6125)

**Comment by zoeyTM** [comment]
Reconciliation failure(s):

![Image](https://github.com/NomicFoundation/ignition/assets/14796043/267a698b-0221-4ddd-a6ac-2b862d4dd96b)

**Comment by zoeyTM** [comment]
On-chain revert error:

![Image](https://github.com/NomicFoundation/ignition/assets/14796043/78816d2a-99df-4646-9054-b7ca0a0368a1)

**Comment by kanej** [comment]
We are running with these versions for `v0.1.0`, and will look to improve them next release.
