### ISSUE TITLE
nonce check initial setup

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/ignition#366]
Consider whether the initial setup of the nonce checks should be the place where inital nonce allocation is handled.

We should consider breaking out nonce management per account from the chain dispatcher and integrating it with the inital nonce check.

## TODO

- [ ] more complex nonce checks doing call and send data and static call contract at
- [ ] Refactor out nonce allocation state from chain dispatcher

**Comment by alcuadrado** [comment]
This is no longer relevant
