### ISSUE TITLE
Revamp journal data structure

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/ignition#6]
The journal we are using right now has several issues:

- It's a JSON, which means that each time it's updated the whole file needs to be read and written
- For a given transaction within an executor, it only keeps track of the last try, but it should keep previous attempts too (for example, to handle the race condition where the gas price of a transaction is bumped but just at that moment the "replaced" transaction is mined).
- It's unclear what happens if there's a problem during writing.

I'm not sure what the right data structure for this would be, so some research is needed. One idea is to have an append-only structure with some guarantee of having "atomic" appends (I have no idea how to implement this though)

**Comment by kanej** [comment]
We switched to line-orientated json so we are append only.
