### ISSUE TITLE
Better handling of legacy vs eip-1559 txs

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/ignition#8]
The gas price related logic is a mess. We should use eip-1559 transactions everywhere if possible, but at the same time Ignition should work fine in non-London environments.

**Comment by kanej** [comment]
@morgansliman I know we talked about this, but is it something we still have to do?

**Comment by alcuadrado** [comment]
An update: #387 has support for EIP1159, and not legacy txs.

**Comment by alcuadrado** [comment]
Done in #387
